### ISSUE TITLE
Start and end addresses have spurious slashes

### ISSUE THREAD

**Issue by codebje** [APNIC-net/rdapd#10]
The start and end addresses of both IPv4 and IPv6 records have spurious leading forward slashes.

    objectClassName: "ip network",
    country: "AU",
    ipVersion: "v6",
    entities: [],
    startAddress: "/0:0:0:0:0:0:0:0",
    name: "ROOT",
    handle: "0::/0",
    type: "ALLOCATED PORTABLE",
    endAddress: "/ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",

**Comment by tlm** [comment]
Fixed
